// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALZFI_CqBQRGFLCsDN-4NRL6A46NIW3Hc',
    appId: '1:146095455614:web:ce752c79856407b729872f',
    messagingSenderId: '146095455614',
    projectId: 'leet-scroll-8ee16',
    authDomain: 'leet-scroll-8ee16.firebaseapp.com',
    storageBucket: 'leet-scroll-8ee16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXZMf8FIOHVvhUDWj_rvVb-2zRA9yKOw',
    appId: '1:146095455614:android:99258f7f0465db5129872f',
    messagingSenderId: '146095455614',
    projectId: 'leet-scroll-8ee16',
    storageBucket: 'leet-scroll-8ee16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSLshwQTOo-F2Mfi5nXwkSKii9zd9jB3Y',
    appId: '1:146095455614:ios:929145af87a7e70229872f',
    messagingSenderId: '146095455614',
    projectId: 'leet-scroll-8ee16',
    storageBucket: 'leet-scroll-8ee16.firebasestorage.app',
    iosClientId:
        '146095455614-oouveri2c4pore0utd8oi73usoc0vsve.apps.googleusercontent.com',
    iosBundleId: 'com.venkey.leetscroll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSLshwQTOo-F2Mfi5nXwkSKii9zd9jB3Y',
    appId: '1:146095455614:ios:929145af87a7e70229872f',
    messagingSenderId: '146095455614',
    projectId: 'leet-scroll-8ee16',
    storageBucket: 'leet-scroll-8ee16.firebasestorage.app',
    iosClientId:
        '146095455614-oouveri2c4pore0utd8oi73usoc0vsve.apps.googleusercontent.com',
    iosBundleId: 'com.venkey.leetscroll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALZFI_CqBQRGFLCsDN-4NRL6A46NIW3Hc',
    appId: '1:146095455614:web:6d76a879c47ecb0329872f',
    messagingSenderId: '146095455614',
    projectId: 'leet-scroll-8ee16',
    authDomain: 'leet-scroll-8ee16.firebaseapp.com',
    storageBucket: 'leet-scroll-8ee16.firebasestorage.app',
  );
}
